   [build]
     command   = "npm run build"   # Netlify 将执行的构建命令
     publish   = ".next"           # 插件会自动处理，无需改动
     environment = { NODE_VERSION = "18" }  # 根据你本地 Node 版本填
     base      = "."               # 代码位于仓库根目录

   [[plugins]]
     package = "@netlify/plugin-nextjs"