   [build]
     command   = "npm run build"   # Netlify 将执行的构建命令
     publish   = ".next"           # 插件会自动处理，无需改动
     base      = "."               # 代码位于仓库根目录

   [build.environment]
     NODE_VERSION = "18"
     NODE_ENV = "production"

   [[plugins]]
     package = "@netlify/plugin-nextjs"